### ISSUE TITLE
FYI: Canary update broke it

### ISSUE THREAD

**Issue by mathiasbynens** [ebidel/lighthouse-hue#1]
The kiosk breaks subtly in Chrome Canary 63.0.3207.0. Worked fine in yesterday’s version. (Found out the hard way at [GDD Europe](https://developers.google.com/events/gdd-europe/).)

Entering a URL starts to run the tests, but they hang forever.

Our hotfix was to rename the `Google Chrome Canary` directory to something else, to force the script to fall back to stable Chrome. Should we change the default to stable Chrome, or remove Canary support from the code at this point?

cc @devnook

**Comment by ebidel** [comment]
Aw, sorry Canary broke you. chrome-launcher accepts a `chromePath` property or `CHROME_PATH` env var which is a path to a chrome binary. 

https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher#launch-options

Cool that you guys are using the project. Other than that, how did it go?

**Comment by ebidel** [comment]
Ok, modernized LH to 2.4.0 and added support for chrome-launcher's `CHROME_PATH`. You can run the app with it to use a different version of Chrome.

https://github.com/ebidel/lighthouse-hue#running-stable-chrome
